# This file was generated by GoReleaser. DO NOT EDIT.
cask "corg" do
  binary "corg", target: "kubectl-corg"

  version "0.0.16"

  on_macos do
    on_arm do
      sha256 "7b5fa5d2696415c0b38970db235acb399ca83262a0e0613aa50aca174b56f373"
      url "https://github.com/clevyr/borgbase-operator/releases/download/v#{version}/corg_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "655a2194a928869c570b13faba73bf870ecd9d82ee8ef4fc893fd9ce5fc195d3"
      url "https://github.com/clevyr/borgbase-operator/releases/download/v#{version}/corg_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c047e78bf6e8fd5a6ce354aa129bfdf2900a583d69d0f1016e6ae8d0a551884e"
      url "https://github.com/clevyr/borgbase-operator/releases/download/v#{version}/corg_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fc954a4c3b8aa039a2b3ba023b514bbcf7d2185137b7f5e3ff50764e01773329"
      url "https://github.com/clevyr/borgbase-operator/releases/download/v#{version}/corg_#{version}_linux_amd64.tar.gz"
    end
  end

  name "corg"
  desc "Companion CLI for the Clevyr borgbase operator"
  homepage "https://github.com/clevyr/borgbase-operator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "corg"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/corg"]
    end
  end

  # No zap stanza required
end
