# This file was generated by GoReleaser. DO NOT EDIT.
cask "corg" do
  binary "corg", target: "kubectl-corg"

  version "0.0.17"

  on_macos do
    on_arm do
      sha256 "ba6011306badb359bf3bd42d2e59b1199fc50c8918d7203c622fbb6171f78a32"
      url "https://github.com/clevyr/borgbase-operator/releases/download/v#{version}/corg_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6abe09e357fe342936d5f4ce329c42315294abd7d79fd15b1e3371147b48c706"
      url "https://github.com/clevyr/borgbase-operator/releases/download/v#{version}/corg_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d0cdece6f5d18126cda53cec47446b5f6f0d63fc5d27f9c9479840df4c6ef4ff"
      url "https://github.com/clevyr/borgbase-operator/releases/download/v#{version}/corg_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cc5139c71bd81a5ca353d217c1ed3d06557b227da0865493749c5c0b303ec9c4"
      url "https://github.com/clevyr/borgbase-operator/releases/download/v#{version}/corg_#{version}_linux_amd64.tar.gz"
    end
  end

  name "corg"
  desc "Companion CLI for the Clevyr borgbase operator"
  homepage "https://github.com/clevyr/borgbase-operator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "corg"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/corg"]
    end
  end

  # No zap stanza required
end
