# This file was generated by GoReleaser. DO NOT EDIT.
cask "corg" do
  binary "corg", target: "kubectl-corg"

  version "0.0.15"

  on_macos do
    on_arm do
      sha256 "31e267ed855bda72687eaaa51d465cc096de7e7789ddd5443225161d71a391f8"
      url "https://github.com/clevyr/borgbase-operator/releases/download/v#{version}/corg_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4aa018b397e4c0e18a16aef2ea166fcd57f781df7a9cef0cc94b83fb8ab0487b"
      url "https://github.com/clevyr/borgbase-operator/releases/download/v#{version}/corg_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cbbde940acd3060472f66a96646c1b09ff87ef330f880e08d2f0b8857ec8970f"
      url "https://github.com/clevyr/borgbase-operator/releases/download/v#{version}/corg_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9f946114c77b088738fa18273e1bf0ec4bc8c4d7318298df56d168f1fd52ea6a"
      url "https://github.com/clevyr/borgbase-operator/releases/download/v#{version}/corg_#{version}_linux_amd64.tar.gz"
    end
  end

  name "corg"
  desc "Companion CLI for the Clevyr borgbase operator"
  homepage "https://github.com/clevyr/borgbase-operator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "corg"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/corg"]
    end
  end

  # No zap stanza required
end
