# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubedb" do
  version "1.20.0"

  on_macos do
    on_arm do
      sha256 "53b0e86cf590c20b02d7e0a39f44b79c4d8401704ff30bf801bab546357da458"
      url "https://github.com/clevyr/kubedb/releases/download/v#{version}/kubedb_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "89c739e624b31e9c6c57448d9d3d4b39f79ee1debd6e95073d9ec64a9a8ebae2"
      url "https://github.com/clevyr/kubedb/releases/download/v#{version}/kubedb_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ce85845d312d9bed1b34d10e51f7aeffd9214aec42a0ad2c97b09934bdaf0c70"
      url "https://github.com/clevyr/kubedb/releases/download/v#{version}/kubedb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6f7fbcf66198ab7451148216d38375d2d6b3ee3dffe627d973fc623d2333bfc1"
      url "https://github.com/clevyr/kubedb/releases/download/v#{version}/kubedb_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kubedb"
  desc "Painlessly work with Kubernetes databases"
  homepage "https://github.com/clevyr/kubedb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubedb"
  manpage "manpages/kubedb-dump.1.gz"
  manpage "manpages/kubedb-exec.1.gz"
  manpage "manpages/kubedb-port-forward.1.gz"
  manpage "manpages/kubedb-restore.1.gz"
  manpage "manpages/kubedb-status.1.gz"
  manpage "manpages/kubedb.1.gz"
  bash_completion "completions/bash/kubedb"
  fish_completion "completions/fish/kubedb.fish"
  zsh_completion "completions/zsh/_kubedb"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubedb"]
    end
  end

  # No zap stanza required
end
