# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubedb" do
  version "1.20.1"

  on_macos do
    on_arm do
      sha256 "88ba8bf0dedac387bd1c298b16031f3b728ecc7be1cbcf993191b39c4b0e7ca5"
      url "https://github.com/clevyr/kubedb/releases/download/v#{version}/kubedb_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a8ac3bbcf7fb4afe69f0d4d2bbd0cae7c1d2fd5eaaa4bccaa6ba636948e3f0bc"
      url "https://github.com/clevyr/kubedb/releases/download/v#{version}/kubedb_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "736282f8f6168ec6e87ec2ef05cb6f082d313f3dde34a244d8b4db223a7ba524"
      url "https://github.com/clevyr/kubedb/releases/download/v#{version}/kubedb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ec7d659ea94bb6d750d1b79f8c195965c225742f40d9683a7357c449e2cef11b"
      url "https://github.com/clevyr/kubedb/releases/download/v#{version}/kubedb_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kubedb"
  desc "Painlessly work with Kubernetes databases"
  homepage "https://github.com/clevyr/kubedb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubedb"
  manpage "manpages/kubedb-dump.1.gz"
  manpage "manpages/kubedb-exec.1.gz"
  manpage "manpages/kubedb-port-forward.1.gz"
  manpage "manpages/kubedb-restore.1.gz"
  manpage "manpages/kubedb-status.1.gz"
  manpage "manpages/kubedb.1.gz"
  bash_completion "completions/bash/kubedb"
  fish_completion "completions/fish/kubedb.fish"
  zsh_completion "completions/zsh/_kubedb"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubedb"]
    end
  end

  # No zap stanza required
end
