# This file was generated by GoReleaser. DO NOT EDIT.
cask "yampl" do
  version "0.10.1"

  on_macos do
    on_arm do
      sha256 "2aa22195ebc5768cf9cfcd8b3bcc7e9fda96229d4e2cd9570322b743e0140097"
      url "https://github.com/clevyr/yampl/releases/download/v#{version}/yampl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "83f72b9ec954ecd605a6a4fae1396aecfa6d1921351d901660383ff9f4418042"
      url "https://github.com/clevyr/yampl/releases/download/v#{version}/yampl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c903e2e555081d3eaedff2e6727149733cd169e7bdd25891a845a68b0b3c579e"
      url "https://github.com/clevyr/yampl/releases/download/v#{version}/yampl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1fe39e7afeaf6f9d06861c0aa4d6d793746cef4e8799669396d6248e508b187b"
      url "https://github.com/clevyr/yampl/releases/download/v#{version}/yampl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "yampl"
  desc "Yaml templating via line-comments"
  homepage "https://github.com/clevyr/yampl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yampl"
  manpage "manpages/yampl.1.gz"
  bash_completion "completions/bash/yampl"
  fish_completion "completions/fish/yampl.fish"
  zsh_completion "completions/zsh/_yampl"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yampl"]
    end
  end

  # No zap stanza required
end
