# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubedb < Formula
  desc "Painlessly work with Kubernetes databases"
  homepage "https://github.com/clevyr/kubedb"
  version "1.13.3"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/clevyr/kubedb/releases/download/v1.13.3/kubedb_1.13.3_darwin_amd64.tar.gz"
      sha256 "71d2568fd9a690ca2f8d48f69155cb641a7f580540ecd257ed8a505df8c02956"

      def install
        bin.install "kubedb"
        man1.install "manpages/kubedb.1.gz"
        man1.install "manpages/kubedb-dump.1.gz"
        man1.install "manpages/kubedb-exec.1.gz"
        man1.install "manpages/kubedb-port-forward.1.gz"
        man1.install "manpages/kubedb-restore.1.gz"
        man1.install "manpages/kubedb-status.1.gz"
        bash_completion.install "completions/kubedb.bash" => "kubedb"
        zsh_completion.install "completions/kubedb.zsh" => "_kubedb"
        fish_completion.install "completions/kubedb.fish"
      end
    end
    on_arm do
      url "https://github.com/clevyr/kubedb/releases/download/v1.13.3/kubedb_1.13.3_darwin_arm64.tar.gz"
      sha256 "f0462f6cd961aebb98dbe29df06ca1950d2406bde727a60b19336c851b02e11e"

      def install
        bin.install "kubedb"
        man1.install "manpages/kubedb.1.gz"
        man1.install "manpages/kubedb-dump.1.gz"
        man1.install "manpages/kubedb-exec.1.gz"
        man1.install "manpages/kubedb-port-forward.1.gz"
        man1.install "manpages/kubedb-restore.1.gz"
        man1.install "manpages/kubedb-status.1.gz"
        bash_completion.install "completions/kubedb.bash" => "kubedb"
        zsh_completion.install "completions/kubedb.zsh" => "_kubedb"
        fish_completion.install "completions/kubedb.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clevyr/kubedb/releases/download/v1.13.3/kubedb_1.13.3_linux_amd64.tar.gz"
        sha256 "a5176fd100be8ca54debd29247258108ca6c66455ee60d6f9639f416b3cf0e68"

        def install
          bin.install "kubedb"
          man1.install "manpages/kubedb.1.gz"
          man1.install "manpages/kubedb-dump.1.gz"
          man1.install "manpages/kubedb-exec.1.gz"
          man1.install "manpages/kubedb-port-forward.1.gz"
          man1.install "manpages/kubedb-restore.1.gz"
          man1.install "manpages/kubedb-status.1.gz"
          bash_completion.install "completions/kubedb.bash" => "kubedb"
          zsh_completion.install "completions/kubedb.zsh" => "_kubedb"
          fish_completion.install "completions/kubedb.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clevyr/kubedb/releases/download/v1.13.3/kubedb_1.13.3_linux_arm64.tar.gz"
        sha256 "a7dc122fae33dc1c479b4177235cb6f55da7512af2698883c2a948c3d1011392"

        def install
          bin.install "kubedb"
          man1.install "manpages/kubedb.1.gz"
          man1.install "manpages/kubedb-dump.1.gz"
          man1.install "manpages/kubedb-exec.1.gz"
          man1.install "manpages/kubedb-port-forward.1.gz"
          man1.install "manpages/kubedb-restore.1.gz"
          man1.install "manpages/kubedb-status.1.gz"
          bash_completion.install "completions/kubedb.bash" => "kubedb"
          zsh_completion.install "completions/kubedb.zsh" => "_kubedb"
          fish_completion.install "completions/kubedb.fish"
        end
      end
    end
  end
end
