# This file was generated by GoReleaser. DO NOT EDIT.
class Scaffold < Formula
  desc ""
  homepage ""
  version "0.3.14"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/clevyr/scaffold/releases/download/v0.3.14/scaffold_0.3.14_Darwin_x86_64.tar.gz"
    sha256 "90ef289ab69d19ffa024b305c2deb5472bf6b379e5537670749c2eff4675871d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/clevyr/scaffold/releases/download/v0.3.14/scaffold_0.3.14_Linux_x86_64.tar.gz"
    sha256 "5b7a4260301803678bf0440e86398e1ff0bf2391e3133d5851e544824b673b03"
  end

  def install
    bin.install "scaffold"
  end
end
