# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scaffold < Formula
  desc ""
  homepage ""
  version "0.5.6"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clevyr/scaffold/releases/download/v0.5.6/scaffold_0.5.6_Darwin_x86_64.tar.gz"
      sha256 "c5c3a35f3f3f9493f6254d958d2f7f1ebbde4eb1212450a69f206d98f78ff649"
    end
    if Hardware::CPU.arm?
      url "https://github.com/clevyr/scaffold/releases/download/v0.5.6/scaffold_0.5.6_Darwin_arm64.tar.gz"
      sha256 "5904c7dfd9c4bbfd548371c67f2927e82292dfb4c4fafe0d7a86f07ea35d0ef2"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/clevyr/scaffold/releases/download/v0.5.6/scaffold_0.5.6_Linux_x86_64.tar.gz"
      sha256 "a1d7de4fbb0c9a7558a147ee776b86cc898091a908430ce5e601824477c5ff4f"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/clevyr/scaffold/releases/download/v0.5.6/scaffold_0.5.6_Linux_armv6.tar.gz"
      sha256 "fc5e526afcb835c13fbc8cecd196fa36ad7e50f9ee4f07c2fe085b8c01818302"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clevyr/scaffold/releases/download/v0.5.6/scaffold_0.5.6_Linux_arm64.tar.gz"
      sha256 "397f80d3f73276c4506b02e0b074d8faffba9bf209e62ad6de7c709d91356aec"
    end
  end

  def install
    bin.install "scaffold"
  end
end
