# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yampl < Formula
  desc "Yaml templating via line-comments"
  homepage "https://github.com/clevyr/yampl"
  version "0.8.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/clevyr/yampl/releases/download/v0.8.0/yampl_0.8.0_darwin_amd64.tar.gz"
      sha256 "45d082f95d40169acf55235b889c78918d206fa4eca57280e1869dee83d6d0c0"

      def install
        bin.install "yampl"
        man1.install Dir["manpages/*"]
        bash_completion.install Dir["completions/bash/*"]
        zsh_completion.install Dir["completions/zsh/*"]
        fish_completion.install Dir["completions/fish/*"]
      end
    end
    on_arm do
      url "https://github.com/clevyr/yampl/releases/download/v0.8.0/yampl_0.8.0_darwin_arm64.tar.gz"
      sha256 "51cac67087962eb1621065d17b01d7694dcf89ef21771b3441575dbf78648d58"

      def install
        bin.install "yampl"
        man1.install Dir["manpages/*"]
        bash_completion.install Dir["completions/bash/*"]
        zsh_completion.install Dir["completions/zsh/*"]
        fish_completion.install Dir["completions/fish/*"]
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clevyr/yampl/releases/download/v0.8.0/yampl_0.8.0_linux_amd64.tar.gz"
        sha256 "7b7a3a4e1c2ddf1642f571a3129a73689519db4615f28232b88f5a257f539cca"

        def install
          bin.install "yampl"
          man1.install Dir["manpages/*"]
          bash_completion.install Dir["completions/bash/*"]
          zsh_completion.install Dir["completions/zsh/*"]
          fish_completion.install Dir["completions/fish/*"]
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clevyr/yampl/releases/download/v0.8.0/yampl_0.8.0_linux_arm64.tar.gz"
        sha256 "bd03d6165e9a116cb197be11b21d3b7ef152dabae7539ef98aa63d94dc2b6dbb"

        def install
          bin.install "yampl"
          man1.install Dir["manpages/*"]
          bash_completion.install Dir["completions/bash/*"]
          zsh_completion.install Dir["completions/zsh/*"]
          fish_completion.install Dir["completions/fish/*"]
        end
      end
    end
  end
end
