# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yampl < Formula
  desc ""
  homepage ""
  version "0.3.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/clevyr/yampl/releases/download/v0.3.4/yampl_0.3.4_Darwin_arm64.tar.gz"
      sha256 "5decb636eeb07be6041f2937a3eaea882f892226be2478624dd2f9b2e5820cc4"

      def install
        bin.install "yampl"
        output = Utils.safe_popen_read("#{bin}/yampl", "--completion=bash")
        (bash_completion/"yampl").write output
        output = Utils.safe_popen_read("#{bin}/yampl", "--completion=zsh")
        (zsh_completion/"_yampl").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/clevyr/yampl/releases/download/v0.3.4/yampl_0.3.4_Darwin_x86_64.tar.gz"
      sha256 "02c724120a1249cecbeb3dc0018db096cc35e9f9087bfa6b5ab9fa7ffe0d3c80"

      def install
        bin.install "yampl"
        output = Utils.safe_popen_read("#{bin}/yampl", "--completion=bash")
        (bash_completion/"yampl").write output
        output = Utils.safe_popen_read("#{bin}/yampl", "--completion=zsh")
        (zsh_completion/"_yampl").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/clevyr/yampl/releases/download/v0.3.4/yampl_0.3.4_Linux_x86_64.tar.gz"
      sha256 "218329e217abe4dda38f379f7c22bf5ecdf6224d40fb26132a434e47af55eb3e"

      def install
        bin.install "yampl"
        output = Utils.safe_popen_read("#{bin}/yampl", "--completion=bash")
        (bash_completion/"yampl").write output
        output = Utils.safe_popen_read("#{bin}/yampl", "--completion=zsh")
        (zsh_completion/"_yampl").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clevyr/yampl/releases/download/v0.3.4/yampl_0.3.4_Linux_arm64.tar.gz"
      sha256 "f140ea51f8d46fe617b14c436d6abeca294b36979a5e7d0af7ea81aae272fbd9"

      def install
        bin.install "yampl"
        output = Utils.safe_popen_read("#{bin}/yampl", "--completion=bash")
        (bash_completion/"yampl").write output
        output = Utils.safe_popen_read("#{bin}/yampl", "--completion=zsh")
        (zsh_completion/"_yampl").write output
      end
    end
  end
end
