# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yampl < Formula
  desc ""
  homepage ""
  version "0.3.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clevyr/yampl/releases/download/v0.3.6/yampl_0.3.6_Darwin_x86_64.tar.gz"
      sha256 "bea151ffe8c4f7f25ee3988a0c1a34c304462c3f0ab82b58adffc0cac4970b2d"

      def install
        bin.install "yampl"
        output = Utils.safe_popen_read("#{bin}/yampl", "--completion=bash")
        (bash_completion/"yampl").write output
        output = Utils.safe_popen_read("#{bin}/yampl", "--completion=zsh")
        (zsh_completion/"_yampl").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/clevyr/yampl/releases/download/v0.3.6/yampl_0.3.6_Darwin_arm64.tar.gz"
      sha256 "ccb73e94928c63db14fe4ad94bece330ad8f53c230b3c5ef89c3ab1a89a8a83f"

      def install
        bin.install "yampl"
        output = Utils.safe_popen_read("#{bin}/yampl", "--completion=bash")
        (bash_completion/"yampl").write output
        output = Utils.safe_popen_read("#{bin}/yampl", "--completion=zsh")
        (zsh_completion/"_yampl").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clevyr/yampl/releases/download/v0.3.6/yampl_0.3.6_Linux_arm64.tar.gz"
      sha256 "4e14780e394d71d8a03656aa65b389daebe845c47e7a4ce11f06aa6e9a5f310e"

      def install
        bin.install "yampl"
        output = Utils.safe_popen_read("#{bin}/yampl", "--completion=bash")
        (bash_completion/"yampl").write output
        output = Utils.safe_popen_read("#{bin}/yampl", "--completion=zsh")
        (zsh_completion/"_yampl").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/clevyr/yampl/releases/download/v0.3.6/yampl_0.3.6_Linux_x86_64.tar.gz"
      sha256 "ac0799abb053e00ffc05015901c5cbbccf9f800bc602536810d492909f92e6f3"

      def install
        bin.install "yampl"
        output = Utils.safe_popen_read("#{bin}/yampl", "--completion=bash")
        (bash_completion/"yampl").write output
        output = Utils.safe_popen_read("#{bin}/yampl", "--completion=zsh")
        (zsh_completion/"_yampl").write output
      end
    end
  end
end
